### ISSUE TITLE
PIG extraction fails

### ISSUE THREAD

**Issue by olivier1980** [Daivuk/Descent-Extractor#1]
I'm trying to get all textures, but this doesn't seem to be working

**Comment by Daivuk** [comment]
Hi, I just tried it out and indeed it doesn't seem to be working anymore. Unfortunately, I did only a single commit of this so I don't have a history of where it stopped working... will be hard to investigate years later. I am attempting to check it out.

**Comment by Daivuk** [comment]
It is fixed

**Comment by olivier1980** [comment]
damn that was fast..thanks!
